name: smart_pantry
description: "A smart pantry management app with barcode scanning"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^4.0.0
  http: ^1.2.0
  flutter_riverpod: 2.6.1
  permission_handler: ^11.0.1
  flutter_dotenv: ^5.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env